# Site settings
title: 901 Thoughts
description: > # this means to ignore newlines until "baseurl:"
  Personal website for Kyle Martin.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://901thoughts.com" # the base hostname & protocol for your site
twitter_username: kylemartin901
github_username:  kylemartin901

# Collections
collections:
  blog:
    output: true
  projects:
    output: true
  

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
